//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Client.Alarms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlarmsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlarmsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mu.Client.Alarms.AlarmsResources", typeof(AlarmsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        public static string AlarmsRibbonController_Header {
            get {
                return ResourceManager.GetString("AlarmsRibbonController_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteAlarmAction_Action {
            get {
                return ResourceManager.GetString("DeleteAlarmAction_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new alarm.
        /// </summary>
        public static string DeleteAlarmAction_Description {
            get {
                return ResourceManager.GetString("DeleteAlarmAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditAlarmAction_Action {
            get {
                return ResourceManager.GetString("EditAlarmAction_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new alarm.
        /// </summary>
        public static string EditAlarmAction_Description {
            get {
                return ResourceManager.GetString("EditAlarmAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewAlarmAction_Action {
            get {
                return ResourceManager.GetString("NewAlarmAction_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new alarm.
        /// </summary>
        public static string NewAlarmAction_Description {
            get {
                return ResourceManager.GetString("NewAlarmAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New from.
        /// </summary>
        public static string NewFromAlarmAction_Action {
            get {
                return ResourceManager.GetString("NewFromAlarmAction_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new alarm.
        /// </summary>
        public static string NewFromAlarmAction_Description {
            get {
                return ResourceManager.GetString("NewFromAlarmAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowAlarmAction_Action {
            get {
                return ResourceManager.GetString("ShowAlarmAction_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new alarm.
        /// </summary>
        public static string ShowAlarmAction_Description {
            get {
                return ResourceManager.GetString("ShowAlarmAction_Description", resourceCulture);
            }
        }
    }
}
